name: build-docker

on:
  push:
    branches: ["master"]

jobs:
  build:
    permissions:
      packages: write
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Login to quay.io Docker Image Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: make docker-build
